 services:
  - type: web
    name: lovely-glaze-makeup-studio
    env: docker
    plan: free
    dockerfilePath: ./RenderDockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d1ocks6r433s73c6hpq0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: db_lovelyglazemakeupstudio
      - key: DB_USERNAME
        value: db_lovelyglazemakeupstudio_user
      - key: DB_PASSWORD
        value: NivmBh9dMsetIkULPk0pI3LVl7DJ6RTl
